# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        OSBOX_BOARD: nanopineo2black
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell 
      - name: Run a multi-line script
        run: |
          mkdir -p ./build/output/images
          touch ./build/output/images/osbox-${{ env.OSBOX_BOARD }}.tar.gz
          #git clone --depth 1 https://github.com/armbian/build  
          #ls -latr 
          #ls -latr build
          #mkdir -p ./build/userpatches
          #ls -latr build/userpatches
          #cp ./customize-image.sh ./build/userpatches/customize-image.sh
          #cd build
          #./compile.sh BOARD=${{ env.OSBOX_BOARD }} HOST=osbox BRANCH=current RELEASE=focal BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=prebuilt COMPRESS_OUTPUTIMAGE=sha,gpg,img
          #ls -latr ./output/images
          #cd ..
          tar -zcvf osbox-${{ env.OSBOX_BOARD }}.tar.gz ./build/output/images
          ls -latr .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          # The URL for uploading assets to the release
          upload_url: osbox-${{ env.OSBOX_BOARD }}.tar.gz
          # The path to the asset you want to upload
          asset_path: osbox-${{ env.OSBOX_BOARD }}.tar.gz
          # The name of the asset you want to upload
          asset_name: osbox-${{ env.OSBOX_BOARD }}.tar.gz
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: application/gzip
